# see https://docs.travis-ci.com/user/languages/android/
language: android
sudo: false
jdk:
  - oraclejdk8
android:
  components:
    - build-tools-27.0.3
    - android-27
    - extra-android-m2repository
script:
  - ./gradlew assembleDebug