# see https://docs.travis-ci.com/user/languages/android/
language: android
sudo: false
jdk:
  - oraclejdk8
android:
  components:
    - platform-tools
    - build-tools-29.0.3
    - android-29
  licenses:
    - 'android-sdk-license-.+'
    - 'android-sdk-preview-license-.+'
script:
  #- ./gradlew assembleDebug --info
  - ./gradlew assembleRelease --info