# see https://docs.travis-ci.com/user/languages/android/
language: android
sudo: false
jdk:
  - oraclejdk8
android:
  components:
    - build-tools-29.0.3
    - android-29
    - extra-android-support
    - extra-android-m2repository
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
script:
  - ./gradlew assembleDebug --info